---
metadata:
  name: Rebugit
  short_name: Rebugit
  description: Rebugit - Bug reproduction in minutes
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/code.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: Rebugit
      link: https://rebugit.com
      external: true
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/selfhosted"
      title: ":rocket: Self hosted"
    - order: 2
      path: "/sdks"
      title: ":wrench: SDKs"
    - order: 3
      path: "/containers"
      title: ":wrench: Containers"
#    - order: 3
#      path: "/editing"
#      title: ":writing_hand: Editing Content"
#    - order: 4
#      path: "/deployment"
#      title: ":rocket: Deployment"
#    - order: 5
#      path: "/developing"
#      title: ":computer: Developing"
  links:
#    - text: BooGi
#      link: https://github.com/filipowm/boogi
#    - text: React
#      link: https://reactjs.org
  ignoreIndex: false
  poweredBy:
    trademark: "/assets/gatsby.png"
    name: GatsbyJS
    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  github: https://github.com/rebugit
#  linkedin: https://www.linkedin.com/in/mateusz-filipowicz-437b4768/
  twitter: https://twitter.com/Madeo__

features:
  darkMode:
    enabled: true
    default: false
  editOnRepo:
    location: https://github.com/rebugit/docs
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Matteo Gioioso"
    webMaster: "Matteo Gioioso"
    managingEditor: "Matteo Gioioso"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode:
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
